### ISSUE TITLE
Неэффективно, можно найти средний балл по всей школе и по каждому классу за один проход словаря школы и списков класса.

### ISSUE THREAD

**Issue by denis-trofimov** [Anisimov96/lesso-2#2]
https://github.com/Anisimov96/lesso-2/blob/4a0026d59444ec85c3b58e494e5113f276188cc3/lesson2_for_1.py#L20

**Comment by Anisimov96** [comment]
Переделала задание. Программа находит данные значения за один проход словаря школы и списков класса

**Comment by denis-trofimov** [comment]
https://github.com/Anisimov96/lesso-2/blob/2151ffd2afd0cac27b6c8290d4025af0b01f4c14/lesson2_for_1.py#L26

Почему не среднее по школе равно сумме средних по классам деленное на число классов? 
Число классов ты уже знаешь из длины списка в данном

**Comment by denis-trofimov** [comment]
Рекомендую убрать неиспользуемый код https://github.com/Anisimov96/lesso-2/blob/2151ffd2afd0cac27b6c8290d4025af0b01f4c14/lesson2_for_1.py#L8-L16

Число классов ты уже знаешь из длины списка в данном, 
```
average_mark_school = amount_school / len(school)
```
Есть пр-во для упрощения, лишние переменные с, без average_mark_school, a, b можно переписать, не потеряв в скорости, но улучшить читаемость.
Мы разбирали вечером 3 марта, посмотри пожалуйста https://repl.it/@silarados/week2

**Comment by Anisimov96** [comment]
> Рекомендую убрать неиспользуемый код
> 
> [lesso-2/lesson2_for_1.py](https://github.com/Anisimov96/lesso-2/blob/2151ffd2afd0cac27b6c8290d4025af0b01f4c14/lesson2_for_1.py#L8-L16)
> 
> Lines 8 to 16 in [2151ffd](/Anisimov96/lesso-2/commit/2151ffd2afd0cac27b6c8290d4025af0b01f4c14)
> 
>  list_a = 0 # сумма оценок всей школы 
>  list_b = 0 # количество оценок всей школы 
>   
>  '''for i in school:   
>    list_b += len(i['scores']) 
>    for d in i['scores']: 
>      list_a += d 
>  c = list_a / list_b # средний балл всей школы 
>  print (f'Средний балл по всей школе = {c}')''' 
> Число классов ты уже знаешь из длины списка в данном,
> 
> ```
> average_mark_school = amount_school / len(school)
> ```
> Есть пр-во для упрощения, лишние переменные с, без average_mark_school, a, b можно переписать, не потеряв в скорости, но улучшить читаемость.
> Мы разбирали вечером 3 марта, посмотри пожалуйста https://repl.it/@silarados/week2
